// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obokngywyjhcgkrrjyqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ib2tuZ3l3eWpoY2drcnJqeXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODc3NjksImV4cCI6MjA2NTY2Mzc2OX0.d-zKkgVeALi8ujkQYRKIMJK4jK6JvoPX1P_cJUIumgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);